# Generated by Django 3.2.25 on 2025-12-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.IntegerField(unique=True)),
                ('name', models.CharField(default='name', max_length=30)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
    ]
